name: friendly-calliope

channels:
    - conda-forge

dependencies:
    - calliope >= 0.6.8
    - pip:
        - friendly_data @ git+https://github.com/sentinel-energy/friendly_data.git@efe7431a48f60c6a66d129e12bf83d6f907fdff6